### PR TITLE
Fix issue 26: couchbase_node wait until couchbase is up and running

### PR DESCRIPTION
**Pull request by DennyZhang**
Pull request to fix https://github.com/urbandecoder/couchbase/issues/26

Add retries for couchbase_node action

### CODE REVIEW

**Comment by DennyZhang** [comment]
@juliandunn  would you please review this pull request, and merge it to master?

**Comment by juliandunn** [comment]
@DennyZhang I'd much rather you modify the provider logic to invoke the `endpoint_responding?` [helper](https://github.com/urbandecoder/couchbase/blob/master/libraries/helper.rb#L40) rather than using retries.

**Comment by DennyZhang** [comment]
@juliandunn  yes, that's better. Please review my latest check-in request. Thanks.

**Comment by juliandunn** [comment]
Not like that. I meant why don't you just invoke the retry and block-until-operational logic right in the [provider](https://github.com/urbandecoder/couchbase/blob/master/libraries/node_provider.rb)

**Comment by DennyZhang** [comment]
@juliandunn That's a good idea.

If we can find out the root cause of below strange behavior, we should be fine for current issue.

In server.rb, after we start/restart couchbase service, ruby_block[block_until_operational] shall run immediately.This ruby block will wait for couchbase server be up and running.
https://github.com/urbandecoder/couchbase/blob/master/recipes/server.rb#L131

Only after that, we will run the login of couchbase_node.
https://github.com/urbandecoder/couchbase/blob/master/recipes/server.rb#L134-L140

I tried more than 3 times. However,  ruby_block[block_until_operational] doesn't run before couchbase_node.

**Comment by juliandunn** [comment]
@DennyZhang can you post the output from your run? The problem is that block won't run if the `service` resource is already in the desired state, which is why I suggest moving the invocation right into the `couchbase_node` provider... i.e. before doing any REST API operations against the Couchbase server, make sure it is up and responding.

**Comment by DennyZhang** [comment]
Yes, that's right.

I've run below command, "KITCHEN_YAML=.kitchen.docker.yml kitchen test".

Here is the output: http://pastebin.com/pKT7ZMYT

**Comment by juliandunn** [comment]
Does it not strike you as weird that [this resource](https://github.com/DennyZhang/couchbase/blob/master/recipes/server.rb#L131-L135) is completely skipped?

**Comment by DennyZhang** [comment]
@juliandunn  Updated the commit of pull request.

Probably couchbase-server is already up, but not ready for severing request.

Thus ""ruby_block[block_until_operational]" is not called.

service "couchbase-server" do
  supports :restart => true, :status => true
  action [:enable, :start]
  notifies :create, "ruby_block[block_until_operational]", :immediately
end

**Comment by DennyZhang** [comment]
@juliandunn Do you have any comment or suggestions for current pull request? If possible, please help to merge it to master.

**Comment by kplimack** [comment]
I've got a fix coming for this.  the problem is that the ruby_block is never fired because the service is started by the package-install, not the service-resource... at least version 3.0.0+

**Comment by kplimack** [comment]
fixed in https://github.com/urbandecoder/couchbase/pull/46

**Pull request closed without merging**
